### ISSUE TITLE
Consider use com.amazonaws.auth.DefaultAWSCredentialsProviderChain

### ISSUE THREAD

**Issue by wilddog64** [skhatri/gradle-s3-plugin#10]
Condsider to use [DefaultAWSCredentialsProviderChain](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) for maximum flexiblity.  The DefaultAWSCredentialsProviderChain API call provide a chain all the way from environment variables, java properties, AWS default profile location (~/.aws/config), and AWS instance profile.

**Comment by nborbit** [comment]
+1. Also need the same feature!

**Comment by flossokay** [comment]
There are two pull requests supporting this functionality.  Is there any reason why you haven't merged one of them?  Also, here are the resources for understanding why people may want this functionality. I hope this convinces you to do this!
http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html
http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-roles.html

**Comment by skhatri** [comment]
I have merged the pull request. Will release now.
