### ISSUE TITLE
File into 'link' has size 0

### ISSUE THREAD

**Issue by Cromir** [skhatri/gradle-s3-plugin#5]
I'm not sure it's a issue, but I don't understand what is the "link" param also because the size of a file that I put in it on S3 is always equals to 0. Can you enlighten me about it please?

Thanks
Giulio

**Comment by eranchetz** [comment]
Here too, what is the 'link' property supposed to do?

**Comment by eranchetz** [comment]
OK, after some digging around I found that the gradle-s3-plugin does it work perfectly! 
The redirect is only available via the "s3 static webpage" option. 
This is a walkthorugh from AWS on how to set it up : https://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html
After I set it up it works perfectly.

I think this needs to be added to the documentation somewhere and then this issue should be closed.

**Comment by skhatri** [comment]
sure. pls send a pull request.

**Comment by eranchetz** [comment]
@skhatri where do you think it's best to put this info? in the readme?

**Comment by skhatri** [comment]
sure. readme.

**Comment by eranchetz** [comment]
see PR #7 
(cc @Cromir)
